version: '3.8'

services:
  bundle_app:
    build:
      context: ./
    container_name: bundle_app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '3000:3000'
    expose:
      - '3000'
    networks:
      - bundle_net

networks:
  bundle_net:
    driver: bridge
